# Generated by Django 6.0.1 on 2026-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_variant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.FileField(upload_to='variant_images/'),
        ),
    ]
