# Generated by Django 6.0.1 on 2026-03-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_image_fields_to_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
