# Generated by Django 6.0.1 on 2026-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ImageField(upload_to='variant_images/'),
        ),
    ]
